### ISSUE TITLE
Error with Pretrained Model When Converting to Tensorflow.js

### ISSUE THREAD

**Issue by GregFrench** [idealo/image-super-resolution#1]
Hi,

I am trying to convert the model weights into a json file using the instructions here: https://js.tensorflow.org/tutorials/import-keras.html . The model is able to convert correctly but I keep getting a 'Uncaught (in promise) TypeError: Cannot read property 'model_config' of null' error when trying to load the model in javascript. I think it has something to do with not using model.save() when saving the keras model in python. Any help will be appreciated. Thanks.

**Comment by cfrancesco** [comment]
I'm guessing that the problems might stem from the fact that only the weights are saved, not the entire model. Looking at the checkpoint callback, we have save_weights_only=True

```
        checkpoint_PSNR = ModelCheckpoint(
            self.checkpoint_paths['PSNR'],
            save_weights_only=True,
            verbose=self.verbose,
            save_best_only=True,
            monitor='PSNR',
            mode='max',
        )
```
I'd suggest you to try to load the model, load the weights and then dump the model to a .h5 file with model.save()

Let me know if this helps!

**Comment by GregFrench** [comment]
Hi Francesco,

It worked! Thanks for your help! I'm building a small open source web app using the pre trained model and weights to enable users to do super resolution in the browser. I will let you know when it's ready so you can check it out. Cheers.

**Comment by talvasconcelos** [comment]
Hi @GregFrench i'm trying to use this on tfjs too but i can't seem to make it work. Getting this error:
Error: Error when checking : expected LR to have 4 dimension(s), but got array with shape [128,128,4]

I'm trying to upscale 128x128 images. Could you share a bit more about your process?

**Comment by GregFrench** [comment]
For processing the images in Tensorflow.js I used the same code in JavaScript that the Python implementation was using:

```
let tensor = tf.fromPixels(url).toFloat().div(tf.scalar(255)).expandDims();

let prediction = await model.predict(tensor).clipByValue(0, 1).mul(tf.scalar(255)).data();
```
Where url = the URL of the image or image data from a web form.

I hope that helps!

**Comment by talvasconcelos** [comment]
Lifesaver.... had to some workarounds because i'm on node, not on browser, but super!!

Users load the model on the browser? how long does it take?

**Comment by GregFrench** [comment]
I just timed it and it took 5 minutes to load the model in the browser. You can check out the implementation here using create react app and GitHub pages: https://github.com/GregFrench/super-resolution.

The app also crashes when trying to process images over 150x150 pixels due to some WebGL issue that I was never able to figure out the cause of. So it seems like it is probably best to run inference on the model through a server rather than a browser which is a little disappointing.
