### ISSUE TITLE
TypeError: train() missing 1 required positional argument: 'monitored_metrics'

### ISSUE THREAD

**Issue by ouening** [idealo/image-super-resolution#10]
OS:Win10,64/ Ubuntu18.04
python: 3.6
keras: 2.2.4
tensorflow: 1.13.1(win10), 1.12.0(Ubuntu18.04)

Hi , When I train my own datasets, I got the error like below:
`Traceback (most recent call last):
  File "D:\Files\python\MachineLearning\GAN\ISR_train_153_x2_images.py", line 46, in <module>
    batch_size=16,
TypeError: train() missing 1 required positional argument: 'monitored_metrics'
`
Can someone figure out?

**Comment by cfrancesco** [comment]
It's a little hard to fix unknown custom code such as `ISR_train_153_x2_images.py`.
However, just as the python interpreter mentions, the train function is missing the argument monitored_metrics. Try adding this to the arguments of the train function:
`monitored_metrics={'val_generator_PSNR' : 'max'}`
or, if you are not using neither the VGG nor the Discriminator networks
`monitored_metrics={'val_PSNR' : 'max'}`

I updated the training tutorial, which was missing this parameter. Thank you.

**Comment by ouening** [comment]
> It's a little hard to fix unknown custom code such as `ISR_train_153_x2_images.py`.
> However, just as the python interpreter mentions, the train function is missing the argument monitored_metrics. Try adding this to the arguments of the train function:
> `monitored_metrics={'val_generator_PSNR' : 'max'}`
> or, if you are not using neither the VGG nor the Discriminator networks
> `monitored_metrics={'val_PSNR' : 'max'}`
> 
> I updated the training tutorial, which was missing this parameter. Thank you.

Yeah，I just find the metrics defined in file "ISR/utils/utils.py", I also found a comment error in line 190 in file "ISR/train/trainer.py", I think it should be

`the values are the mode that trigger weights saving ('min' vs 'max').`

not 
`
('mix' vs 'max')
`

**Comment by cfrancesco** [comment]
Good. Yes, thanks for the spotting the typo.
