### ISSUE TITLE
Tiling artifacts when denoising with patch-size parameter

### ISSUE THREAD

**Issue by Jurph** [idealo/image-super-resolution#105]
When denoising and using a patch-size parameter to work within constrained memory, the denoising effect comes with an undesirable tiling artifact. I like the noise reduction I get, but the seams really appear to ruin the output. Am I doing something wrong with the model or is this an unfortunate consequence of having to operate within 2GB of memory? 

![tiling-artifact](https://user-images.githubusercontent.com/7751563/74240936-efd2ae80-4ca8-11ea-9366-63f13cd2256a.PNG)

**Comment by cfrancesco** [comment]
Did you try to increase the padding_size argument? Default is 2, which probably in your case is not enough
```
predict(self, input_image_array, by_patch_of_size=None, batch_size=10, padding_size=2)
```

**Comment by Jurph** [comment]
Spot on. I'm using a larger padding size and getting much cleaner results now. Thanks.
