### ISSUE TITLE
Unable to download sample_weights due to repository being over it's data quota.

### ISSUE THREAD

**Issue by Shadetail** [idealo/image-super-resolution#109]
I got an error message:
> This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Could external download links for these files be provided? 

Edit:
I found this google drive link in issue #59 
https://drive.google.com/drive/folders/1cJLPgGfEuFAQzBKbXQtSGXxLXssw1D9f?usp=sharing

I recommend adding this link to the README.md, so that future adventurers can be spared from spending 2h figuring out what LFS is and how to download such files, just to nearly give up, and grasping at straws, finally dig out the regular download link in an old closed thread.

Edit2:
Much lighter RRDN model, trained with GANs, mentioned in [this comment](https://github.com/idealo/image-super-resolution/issues/37#issuecomment-509606473) has a broken link, and doesn't seem to be included in the google drive either. Does anyone have a working download link to it?

**Comment by cfrancesco** [comment]
Hi,
you're not supposed to use git-lfs any longer. There is an API for model weights now, look at the general readme or the weights readme or the notebook tutorials.
Did you find the info for it on the repo somewhere? If so, please point it out so I can remove it. Thank you!

**Comment by Shadetail** [comment]
I managed to somehow miss the notebooks folder, which was my fault seeing that it is mentioned in the main readme. Notebooks folder was very useful and helped me to get everything working.
rrdn-C4-D3-G32-G032-T10-x4_epoch299 model is insane, the results are too good to be true, yet somehow still true. Thank you for help and for all your hard work!
