### ISSUE TITLE
Script to generate figure grids

### ISSUE THREAD

**Issue by bw0248** [idealo/image-super-resolution#112]
Hi, I was wondering whether you could upload the script to generate the figure grids.
I'm talking about grids like [these](https://raw.githubusercontent.com/idealo/image-super-resolution/master/figures/butterfly_comparison_SR_baseline.png).
I couldn't find them in the repo, maybe I'm overlooking something?
Would be nice to get some inspiration how to produce similar grids, as I feel like they look pretty good!

**Comment by cfrancesco** [comment]
Sorry, I don't version control these. I used the draw rectangle function of PIL https://pillow.readthedocs.io/en/3.0.x/reference/ImageDraw.html

**Comment by bw0248** [comment]
Hey thanks for answering. I actually wrote a script to draw these figures with pillow in the meantime. Good to hear that you used that as well.
