### ISSUE TITLE
Publically accessible bucket for 4x scale weights

### ISSUE THREAD

**Issue by lachlanmcdonald** [idealo/image-super-resolution#116]
Hi,

I noticed in the source that there are [weights trained on a 4x scale](https://github.com/idealo/image-super-resolution/tree/d1b979f42cdd1766ae192a9c7817a597908d1c0a/weights/sample_weights/rrdn-C4-D3-G32-G032-T10-x4/Perceptual). I was hoping these were also available on an S3 Bucket like the other weights in the module -- as it seems Git LFS (at least my Git configuration) cannot retrieve these directly from the repository.

Thanks!

**Comment by cfrancesco** [comment]
This is retrievable with the API, as in the readme. The weights naming is 'gans'

**Comment by lachlanmcdonald** [comment]
Whoops, completely missed it. Thanks @cfrancesco.
