### ISSUE TITLE
can't train RRDN scale x4

### ISSUE THREAD

**Issue by jirat-sumitanun** [idealo/image-super-resolution#119]
Edit: I known it, I need to resize images to 25% of original.
I try to train RDN,RRDN scale x4 with my own jpg Dataset and png DIV2k Dataset but it gave me error
`from ISR.models import RRDN
from ISR.models import Discriminator
from ISR.models import Cut_VGG19
from ISR.train import Trainer

lr_train_patch_size = 40
layers_to_extract = [5, 9]
scale = 4
hr_train_patch_size = lr_train_patch_size * scale

rrdn  = RRDN(arch_params={'C':4, 'D':3, 'G':64, 'G0':64, 'T':10, 'x':scale}, patch_size=lr_train_patch_size)
f_ext = Cut_VGG19(patch_size=hr_train_patch_size, layers_to_extract=layers_to_extract)
discr = Discriminator(patch_size=hr_train_patch_size, kernel_size=3)

loss_weights = {
'generator': 0.0,
'feature_extractor': 0.0833,
'discriminator': 0.01
}
losses = {
'generator': 'mae',
'feature_extractor': 'mse',
'discriminator': 'binary_crossentropy'
}

log_dirs = {'logs': './logs', 'weights': './weights'}

learning_rate = {'initial_value': 0.0004, 'decay_factor': 0.5, 'decay_frequency': 30}

flatness = {'min': 0.0, 'max': 0.15, 'increase': 0.01, 'increase_frequency': 5}

trainer = Trainer(
    generator=rrdn,
    discriminator=discr,
    feature_extractor=f_ext,
    lr_train_dir='data/div2k/DIV2K_train_LR_bicubic/X2/',
    hr_train_dir='data/div2k/DIV2K_train_HR/',
    lr_valid_dir='data/div2k/DIV2K_valid_LR_bicubic/X2/',
    hr_valid_dir='data/div2k/DIV2K_valid_HR/',
    loss_weights=loss_weights,
    learning_rate=learning_rate,
    flatness=flatness,
    dataname='kig2k',
    log_dirs=log_dirs,
    weights_generator=None,
    weights_discriminator=None,
    n_validation=40,
)

trainer.train(
    epochs=5,
    steps_per_epoch=20,
    batch_size=4,
    monitored_metrics={'val_generator_PSNR_Y': 'max'}
)`

`Traceback (most recent call last):
  File "d:/03 MyWorld/python/image-super-resolution/trainRRDN-kigx4.py", line 58, in <module>
    monitored_metrics={'val_generator_PSNR_Y': 'max'}
  File "d:\03 MyWorld\python\image-super-resolution\ISR\train\trainer.py", line 300, in train
    validation_set = self.valid_dh.get_validation_set(batch_size)
  File "d:\03 MyWorld\python\image-super-resolution\ISR\utils\datahandler.py", line 207, in get_validation_set
    batches = self.get_validation_batches(batch_size)
  File "d:\03 MyWorld\python\image-super-resolution\ISR\utils\datahandler.py", line 190, in get_validation_batches
    batches.append(self.get_batch(batch_size, idx, flatness=0.0))
  File "d:\03 MyWorld\python\image-super-resolution\ISR\utils\datahandler.py", line 177, in get_batch
    batch = self._crop_imgs(img, batch_size, flatness)
  File "d:\03 MyWorld\python\image-super-resolution\ISR\utils\datahandler.py", line 125, in _crop_imgs
    crops['hr'] = np.array(crops['hr'])
ValueError: could not broadcast input array from shape (0,0,3) into shape (0)`

**Comment by anilkumarvvss** [comment]
What's the fix for this issue?
