### ISSUE TITLE
ValueError: You are trying to load a weight file containing 154 layers into a model with 148 layers.

### ISSUE THREAD

**Issue by ouening** [idealo/image-super-resolution#12]
Hi, When I finished training my own datasets(train:153 images, val:39 images),I got some weights under folder "wieghts", I tried some of the weights to  predict, but I got errors like below:
`Traceback (most recent call last):
  File "/home/gaoya/Files/python/GAN/ISR_predict_153_x2_images.py", line 17, in <module>
    rdn.model.load_weights('/home/gaoya/Files/python/GAN/weights/rrdn-C4-D3-G64-G064-T10-x2/images/153x2-vgg19-5-9-srgan-large/rrdn-C4-D3-G64-G064-T10-x2_images_153x2-vgg19-5-9-srgan-large-e074.hdf5')
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 1030, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 154 layers into a model with 148 layers.`
What's wrong with this?

**Comment by cfrancesco** [comment]
It seems that you trained a RRDN model (`rrdn-C4-D3-G64-G064-T10-x2`) and you're trying to load the weights into a RDN model (`rdn.model.load_weights`).

I appreciate your activity, but given that this is the second issue you're open regarding you own scripts: read the documentation again and if you open an issue, try to address problems related to the project or package (such as unclear/misleading/imprecise/wrong information) not to your own scripts.

In this case, did you follow our instruction precisely and ended up mixing up the models? Could you point out where the confusion arose?
