### ISSUE TITLE
ISR_Traininig_Tutorial  ValueError: 'a' cannot be empty unless no samples are taken

### ISSUE THREAD

**Issue by digit-jv** [idealo/image-super-resolution#125]
Dear idealo,

I'm try to run the ISR_Traininig_Tutoria.ipynb with grey images (no RGB) and I'm getting this error:
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-293972f21fab> in <module>
     37     weights_generator=None,
     38     weights_discriminator=None,
---> 39     n_validation=40,
     40 )
     41 

C:\ProgramData\Anaconda3\lib\site-packages\ISR\train\trainer.py in __init__(self, generator, discriminator, feature_extractor, lr_train_dir, hr_train_dir, lr_valid_dir, hr_valid_dir, loss_weights, log_dirs, fallback_save_every_n_epochs, dataname, weights_generator, weights_discriminator, n_validation, flatness, learning_rate, adam_optimizer, losses, metrics)
    137             patch_size=self.lr_patch_size,
    138             scale=self.scale,
--> 139             n_validation_samples=n_validation,
    140         )
    141 

C:\ProgramData\Anaconda3\lib\site-packages\ISR\utils\datahandler.py in __init__(self, lr_dir, hr_dir, patch_size, scale, n_validation_samples)
     29         self.patch_size = {'lr': patch_size, 'hr': patch_size * self.scale}
     30         self.logger = get_logger(__name__)
---> 31         self._make_img_list()
     32         self._check_dataset()
     33 

C:\ProgramData\Anaconda3\lib\site-packages\ISR\utils\datahandler.py in _make_img_list(self)
     42         if self.n_validation_samples:
     43             samples = np.random.choice(
---> 44                 range(len(self.img_list['hr'])), self.n_validation_samples, replace=False
     45             )
     46             for res in ['hr', 'lr']:

mtrand.pyx in numpy.random.mtrand.RandomState.choice()

ValueError: 'a' cannot be empty unless no samples are taken`

**Comment by cfrancesco** [comment]
It is because the image list is built by making sure the images have 4 channels, so no images are found.
