### ISSUE TITLE
Fixing grid artifacts when predicting with `by_patch_of_size` and `noise-cancel` weights

### ISSUE THREAD

**Issue by cfhammill** [idealo/image-super-resolution#134]
Thanks for the wonderful package! 

I'm trying to upsample some large DSLR photos, I need to use by `by_patch_of_size` to control memory use

```python
from ISR.models import RDN

rdn = RDN(weights='noise-cancel')
sr_img = rdn.predict(lr_img, by_patch_of_size=300)
```

Input:

![image](https://user-images.githubusercontent.com/7467038/87886829-074b5b80-c9ee-11ea-838a-b5c0d82946bd.png)

Output:

![image](https://user-images.githubusercontent.com/7467038/87886844-23e79380-c9ee-11ea-857b-ee374559b03b.png)

There is a slight grid artifact along the edge of the patches, marked by decreased brightness. The interior of the patches appears brighter than the original image though, so it is possible the edges are the original brightness.

Any ideas for how to remove the artifact? I was thinking I could shift the image down and to the right by 10 pixels and run the prediction again, then shift back and average the two images.

Thanks!

**Comment by cfrancesco** [comment]
Hi, there is a parameter for this that is defaulted to 2: `padding_size=2`.
Use a larger one and it should solve it.

**Comment by cfhammill** [comment]
Ahh I didn't see that options, thanks so much!
