### ISSUE TITLE
How to fine-tune RRDN on own dataset?

### ISSUE THREAD

**Issue by qAp** [idealo/image-super-resolution#135]
Hi
Is there a way to create an `RRDN` for training that already has like the pre-trained weights in `RRDN(weights='gans')` (or any other available pre-trained weights)?

I tried changing the example for training thus:
```
lr_train_patch_size = 40
layers_to_extract = [5, 9]
scale = 2
hr_train_patch_size = lr_train_patch_size * scale

# rrdn  = RRDN(arch_params={'C':4, 'D':3, 'G':64, 'G0':64, 'T':10, 'x':scale}, patch_size=lr_train_patch_size)
rrdn = RRDN(weights='gans', patch_size=lr_train_patch_size)
f_ext = Cut_VGG19(patch_size=hr_train_patch_size, layers_to_extract=layers_to_extract)
discr = Discriminator(patch_size=hr_train_patch_size, kernel_size=3)
```
but it didn't work:
```
 145         if self.discriminator:
--> 146             assert self.lr_patch_size * self.scale == self.discriminator.patch_size
    147             self.adam_optimizer
    148         if self.feature_extractor:

AssertionError: 
```

Thanks

**Comment by cfrancesco** [comment]
Hi,
one issue here is that the gans model was trained on a 4x scale, and that's what's being loaded as a parameter. Unfortunately, this can't be changed as it is defining the network structure.

**Comment by qAp** [comment]
Thanks, I see.  So if I scaled div2k's high-resolution images down by a factor of 4, the above would work.

**Comment by Timmate** [comment]
I've managed to run the training of a pre-trained RRDN with the scale factor of 4 by adding the following line to the code:
`rrdn.patch_size = lr_train_patch_size`
Otherwise, a trainer object couldn't be initialized since `patch_size` was set to None.
@cfrancesco, could you tell me if this is the right way of fine-tuning a pre-trained model on another dataset?
