### ISSUE TITLE
Training using custom dataset

### ISSUE THREAD

**Issue by Kavit212** [idealo/image-super-resolution#139]
Hi, thanks for making your great work available to everyone. 
Is it possible to train the model with my own custom dataset ? 
If so, could you kindly give me some clues on which lines of codes need to be changed to make this possible? 

Thank you very much

**Comment by cfrancesco** [comment]
Hi, it's in the README, under training:
```

trainer = Trainer(
    generator=rrdn,
    discriminator=discr,
    feature_extractor=f_ext,
    lr_train_dir='low_res/training/images',
    hr_train_dir='high_res/training/images',
    lr_valid_dir='low_res/validation/images',
    hr_valid_dir='high_res/validation/images',
    loss_weights=loss_weights,
    learning_rate=learning_rate,
    flatness=flatness,
    dataname='image_dataset',
    log_dirs=log_dirs,
    weights_generator=None,
    weights_discriminator=None,
    n_validation=40,
)
```
just point to your folders. If you have any further issues don't hesitate to ask.

**Comment by Kavit212** [comment]
Thanks for the fast reply!
