### ISSUE TITLE
Question about the patch size

### ISSUE THREAD

**Issue by sangjun04** [idealo/image-super-resolution#145]
Lets say LR input image A and paired HR input image B are used to train the RRDN/RDN model, and the variable lr_patch_size set to  30.

Then is image A randomly cropped into patch size of 30 OR is image A resized (or put into network with input size of 30) to the patch size of 30?

I am trying to fully understand the network but it is bit confusing.

Thank you in advance.

**Comment by cfrancesco** [comment]
Hi,
they are cropped to 30. If I remember correctly, a `batch_size` number of 30x30 patches is extracted from the LR image to form a batch.

**Comment by sangjun04** [comment]
Thank you for the response. One more quick question. Then the patch is generated by cropping an original image at a random location?

**Comment by cfrancesco** [comment]
Yes, batch_size top left corners are randomly chosen from the given image as anchor points for the square patches.

**Comment by sangjun04** [comment]
Thank you so much for the response. I have one more question to ask :p 
Then how do we determine the number of patches to randomly generate in a given image? Is it related to the batch size?

**Comment by cfrancesco** [comment]
It is the batch size, yes. Each batch is made of a number of patches equal to the batch_size, randomly sampled from a single LR image
