### ISSUE TITLE
TypeError: predict() missing 1 required positional argument: 'input_image_array'

### ISSUE THREAD

**Issue by mustaeenqazi** [idealo/image-super-resolution#147]
Hi,
somehow the predict function seems to be not working even though i gave the input image as numpy array but still it gives the error.

![error2](https://user-images.githubusercontent.com/66418760/93667204-49435d00-fa84-11ea-8113-f9de2b299f08.png)

**Comment by cfrancesco** [comment]
You wrongly instantiated the model, do this instead:
`model = RRDN()`

**Comment by mustaeenqazi** [comment]
I got it. Thank you very much
