### ISSUE TITLE
Repository over its data quota

### ISSUE THREAD

**Issue by rookboom** [idealo/image-super-resolution#150]
I am unable to download the model data. I am getting the following error:

```
> git lfs pull
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/idealo/image-super-resolution.git/info/lfs'
```

**Comment by ellerychan** [comment]
This condition still persists.  Is there any other way to obtain the `weights/sample_weights/.../*.hdf5` files for this project?

**Comment by cfrancesco** [comment]
That is an outdated way of getting the weights. 
Please rely on the api call for each model instead, e.g. `model=RRDN(weights='gans')`, as in the readme. 
If you need the weights file, you can save the model manually with `model.save_weights(path)`

**Comment by DonRichards** [comment]
@cfrancesco Just pointing out the documentation suggests `$ > git lfs pull` here --> https://idealo.github.io/image-super-resolution/tutorials/docker/ 
Thanks for the solution, just thought this should probably be updated.
