### ISSUE TITLE
Is it So?

### ISSUE THREAD

**Issue by innat** [idealo/image-super-resolution#159]
I tried to upscale with the following samples, but it seems like things are not as it is as demonstrated in the source. What am I missing? 

```python
from ISR.models import RDN
rdn = RDN(weights='psnr-small')
sr_img = rdn.predict(lr_img)
Image.fromarray(sr_img)
```

![a](https://user-images.githubusercontent.com/17668390/98789756-f1debf00-242c-11eb-8010-b0d09c9e38ec.jpg)

**Comment by cfrancesco** [comment]
Hi,
are you referring to the sample shown at the beginning of the readme?
That is upscaled with the gan model. 
The model you're using here is a smaller and non-adversarial one (MSE driven).

**Comment by innat** [comment]
Sorry, I should update my query. I have already noticed it. However, this time I tried with following set up

**Input**

![double_check](https://user-images.githubusercontent.com/17668390/98836313-bf07eb80-246b-11eb-966d-981f40fb8a42.jpg)

```python
from ISR.models import RDN, RRDN
rdn = RRDN(weights='gans')

img = Image.open('check.jpg')
lr_img = np.array(img)
```

**Expected**
![output](https://user-images.githubusercontent.com/17668390/98836401-d6df6f80-246b-11eb-9e1b-b3510f058bd8.jpg)

But achieving the same as the input but with bigger size. I think I'm misunderstanding. I expect to get a much cleaner image with reasonable upscaling. However, any pointer? Thanks.

**Comment by cfrancesco** [comment]
What do you mean exactly with "same as the input"? 
Is "Expected" the model output or what you expected to get?
If so, the output looks fine to me. Not great, due to the many artifacts, but the model was trained on natural images and the input image is very blurry. You might want to re-train or train further with images closer to what you need.
