### ISSUE TITLE
visible padding border when run RDN artifact-cancelling net with "by_patch_size"

### ISSUE THREAD

**Issue by DeXtmL** [idealo/image-super-resolution#165]
![dccFROM-out](https://user-images.githubusercontent.com/13725477/103003575-fccc5980-456b-11eb-83e9-177dd4e19e46.jpg)
[pic]
just check this out

code:
```
rdn = RDN(weights='noise-cancel')
sr_img = rdn.predict(lr_img, by_patch_of_size=10)
```
using different "by_path_size" produces different sizes of blocks.
SAD

Tested on Ubuntu 18

**Comment by cfrancesco** [comment]
I see no unexpected behavior: it's prediction done by patches (not paths) for images of large size. 
Increase the padding of the patches and or the size of the patches to get rid of this effect.

Feel free to re-open if you encounter some issues.
