### ISSUE TITLE
Error:  original_keras_version = f.attrs['keras_version'].decode('utf8')

### ISSUE THREAD

**Issue by cabustillo13** [idealo/image-super-resolution#171]
If you have this problem and was able to fix this by setting h5py < 3.0.0.

Looks like here was a 3.0 release of h5py recently where they changed how strings are stored/read.
https://docs.h5py.org/en/stable/whatsnew/3.0.html#what-s-new-in-h5py-3-0

So just do this: pip install 'h5py<3.0.0'

**Comment by cabustillo13** [comment]
It is just a tip in case you come across this error.

**Comment by ZhyCong** [comment]
Thank you very much, I fix the error with the help of your tips!
