### ISSUE TITLE
 Unable to open .hdf5 file (file signature not found) 

### ISSUE THREAD

**Issue by Elwarfalli** [idealo/image-super-resolution#21]
Hello,
When I tried to run he perdaction using this piece of code : 

> import tensorflow as tf
> from ISR.models import RDN
> import h5py
> rdn = RDN(arch_params={'C':6, 'D':20, 'G':64, 'G0':64, 'x':2})
> rdn.model.load_weights('weights/sample_weights/rdn-C6-D20-G64-G064-x2/ArtefactCancelling/rdn-C6-D20-G64-G064-x2_ArtefactCancelling_epoch219.hdf5')

I got an error 
 

> ---------------------------------------------------------------------------
> OSError                                   Traceback (most recent call last)
> <ipython-input-2-a974cd0fad24> in <module>
>       3 import h5py
>       4 rdn = RDN(arch_params={'C':6, 'D':20, 'G':64, 'G0':64, 'x':2})
> ----> 5 rdn.model.load_weights('weights/sample_weights/rdn-C6-D20-G64-G064-x2/ArtefactCancelling/rdn-C6-D20-G64-G064-x2_ArtefactCancelling_epoch219.hdf5')
>       6 
>       7 sr_img = rdn.predict(lr_img)
> 
> ~\Anaconda3\lib\site-packages\keras\engine\network.py in load_weights(self, filepath, by_name, skip_mismatch, reshape)
>    1155         if h5py is None:
>    1156             raise ImportError('`load_weights` requires h5py.')
> -> 1157         with h5py.File(filepath, mode='r') as f:
>    1158             if 'layer_names' not in f.attrs and 'model_weights' in f:
>    1159                 f = f['model_weights']
> 
> ~\Anaconda3\lib\site-packages\h5py\_hl\files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, rdcc_nslots, rdcc_nbytes, rdcc_w0, track_order, **kwds)
>     392                 fid = make_fid(name, mode, userblock_size,
>     393                                fapl, fcpl=make_fcpl(track_order=track_order),
> --> 394                                swmr=swmr)
>     395 
>     396             if swmr_support:
> 
> ~\Anaconda3\lib\site-packages\h5py\_hl\files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
>     168         if swmr and swmr_support:
>     169             flags |= h5f.ACC_SWMR_READ
> --> 170         fid = h5f.open(name, flags, fapl=fapl)
>     171     elif mode == 'r+':
>     172         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
> 
> h5py\_objects.pyx in h5py._objects.with_phil.wrapper()
> 
> h5py\_objects.pyx in h5py._objects.with_phil.wrapper()
> 
> h5py\h5f.pyx in h5py.h5f.open()
> 
> OSError: Unable to open file (file signature not found)

So any help please, has anyone faced the same problem? How can I fix it?

Thanks a lot!

**Comment by Elwarfalli** [comment]
@cfrancesco

**Comment by cfrancesco** [comment]
Hi.

did you use `git lfs pull` to download the weights?

**Comment by eob** [comment]
@cfrancesco I'm getting the same error message on the most recent clone of `master`. Are there additional weights that aren't part of the repo?

**Comment by cfrancesco** [comment]
I'm assuming this is closed. Feel free to create a new issue should that not be the problem.

**Comment by sunitasonu** [comment]
hello sir i am  installing pip install git clone https://github.com/idealo/image-super-resolution but i am getting error like this 

Cannot unpack file C:\Users\Tech\AppData\Local\Temp\pip-unpack-empwgs4d\image-super-resolution (downloaded from C:\Users\Tech\AppData\Local\Temp\pip-req-build-7jd1qwye, content-type: text/html; charset=utf-8); cannot detect archive format
Cannot determine archive format of C:\Users\Tech\AppData\Local\Temp\pip-req-build-7jd1qwye

Plz help me sir as soon as possible thank you

**Comment by leowang7** [comment]
Got this issue, any ideas?

$ git lfs pull
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/idealo/image-super-resolution.git/info/lfs'

**Comment by cfrancesco** [comment]
In the latest version it should be possible to get the weights directly when instantiating the model. Like so:
```
from ISR.models import RDN

rdn = RDN(weights='psnr-small')
```

@leowang7 where did you see the reference to `git lfs pull`? It shouldn't be part of the repo any longer..

**Comment by jonathanmv** [comment]
The reference to `git lfs pull` is in the docs under [tutorials/docker](https://idealo.github.io/image-super-resolution/tutorials/docker/)

**Comment by sunitasonu** [comment]
which algorithm you are using . if you are doing super resolution then use
Gan algoritam
