### ISSUE TITLE
Installing is buggy with PIP

### ISSUE THREAD

**Issue by verdoganai** [idealo/image-super-resolution#22]
Hi,
I have tried to train my own dataset; however, I got this error

`TypeError                                 Traceback (most recent call last)
<ipython-input-85-0815a20754c1> in <module>()
         weights_generator=None,
         weights_discriminator=None,
--->      n_validation=40,
     )
     

TypeError: __init__() got an unexpected keyword argument 'flatness'`

Then, I have tried to use !git clone but this time other errors came up. I think you need to upgrade "!pip install ISR" with the latest version for training. If I am wrong, please correct me. Thank you!

**Comment by cfrancesco** [comment]
Hi,
could you post the relevant parts of the script?

**Comment by verdoganai** [comment]
Hi,
https://github.com/idealo/image-super-resolution/blob/master/notebooks/ISR_Traininig_Tutorial.ipynb

Think this file should be updated since your main page does not fit this one in terms of "Trainer" input arguments. 

from ISR.train import Trainer
loss_weights = {
  'generator': 0.0,
  'feature_extractor': 0.0833,
  'discriminator': 0.01
}
losses = {
  'generator': 'mae',
  'feature_extractor': 'mse',
  'discriminator': 'binary_crossentropy'
} 

log_dirs = {'logs': './logs', 'weights': './weights'}

learning_rate = {'initial_value': 0.0004, 'decay_factor': 0.5, 'decay_frequency': 30}

flatness = {'min': 0.0, 'max': 0.15, 'increase': 0.01, 'increase_frequency': 5}

adam_optimizer = {'beta1': 0.9, 'beta2': 0.999, 'epsilon': None}

trainer = Trainer(
    generator=rrdn,
    discriminator=discr,
    feature_extractor=f_ext,
    lr_train_dir='div2k/DIV2K_train_LR_bicubic/X2/',
    hr_train_dir='div2k/DIV2K_train_HR/',
    lr_valid_dir='div2k/DIV2K_train_LR_bicubic/X2/',
    hr_valid_dir='div2k/DIV2K_train_HR/',
    loss_weights=loss_weights,
#    losses=losses,
    learning_rate=learning_rate,
    flatness=flatness,
    log_dirs=log_dirs,
    adam_optimizer=adam_optimizer,
    metrics={'generator': 'PSNR_Y'},
    dataname='div2k',
    weights_generator=None,
    weights_discriminator=None,
    n_validation=40,
)

**Comment by cfrancesco** [comment]
Yep, the pip package was not up-to-date!
