### ISSUE TITLE
Loading Models | AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by ss8319** [idealo/image-super-resolution#228]
I am running the ISR Prediction Tutorial.ipynb on Google Colab using the dataset given.

While running the code to create the model as shown below,
model = RRDN(weights='gans')

It is showing this **error**.
[/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/saving/hdf5_format.py](https://localhost:8080/#) in load_weights_from_hdf5_group(f, layers)
    649   """
    650   if 'keras_version' in f.attrs:
--> 651     original_keras_version = f.attrs['keras_version'].decode('utf8')
    652   else:
    653     original_keras_version = '1'

AttributeError: 'str' object has no attribute 'decode'

In the subsequent, hdf5_format.py file I tried taking off  '.decode('utf8')' but it gives the same error.

**Comment by mrkrcc** [comment]
https://github.com/idealo/image-super-resolution#weights-loading

**Comment by ss8319** [comment]
> https://github.com/idealo/image-super-resolution#weights-loading

Thank you so much! Works for me now
