### ISSUE TITLE
Can't find the model I just trained

### ISSUE THREAD

**Issue by CodeRotation** [idealo/image-super-resolution#25]
Hi, I trained the network by ISR_Traininig_Tutorial.ipynb on Google Colab platform. The training process ended successfully, but I can't find the model. 

Folder "**weights/<actual_train>/<actual_date_time>**" contains only *session_config.yml* file. 

Has anyone encountered this problem?

**Comment by cfrancesco** [comment]
I can confirm, for some reason the model file is not created. I'm not too familiar with the Colab ecosystem, do you have the same issue when training locally?

**Comment by cfrancesco** [comment]
check #26 , does this apply?
