### ISSUE TITLE
Image size limit?

### ISSUE THREAD

**Issue by btahir** [idealo/image-super-resolution#28]
Cool project! What are the limits on how big an input image can be (assuming you are using the Colab Tutorial notebook)?

I tried to run predictions on a 1024x1024 image but got an OOM error. Is there a way to apply Super Resolution to larger images?

**Comment by cfrancesco** [comment]
Hi, thank you very much! 
There is already a discussion regarding this (#14 ). 
I hope to push some code as soon as time allows.
