### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by OzgunKB** [idealo/image-super-resolution#30]
python setup.py install

I run the command.  Installation complete.

Which file will I run now?

**Comment by cfrancesco** [comment]
After you read the documentation (https://idealo.github.io/image-super-resolution/) you can either:
- create a new python script or jupyter notebook, import the classes and use as intended, or
- use it from terminal, from the main project folder as follows:
`python ISR/assistant.py --config config.yml`

**Comment by ManoaNosea** [comment]
'''
λ python ISR\assistant.py  --config config.yml
Traceback (most recent call last):
  File "ISR\assistant.py", line 88, in <module>
    prediction=args['prediction'],
  File "ISR\assistant.py", line 15, in run
    session_type, generator, conf, dataset = setup(config_file, default, training, prediction)
  File "D:\Programs64\Python-3.6.5\lib\site-packages\ISR\utils\utils.py", line 168, in setup
    conf = yaml.load(open(config_file, 'r'), Loader=yaml.FullLoader)
AttributeError: module 'yaml' has no attribute 'FullLoader'
'''
