### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'logs_dir'

### ISSUE THREAD

**Issue by coco-HJ** [idealo/image-super-resolution#39]
How to handle this..? I don't know what should I do..
![스크린샷, 2019-07-15 09-50-58](https://user-images.githubusercontent.com/52692709/61191515-7f4dba00-a6e6-11e9-9eae-6de3fceec2dc.png)

Thank you

**Comment by cfrancesco** [comment]
Could you show the code you are using?

From the screenshot, I would assume you are using the Trainer class, that accepts the argument `log_dirs`(which defaults to `{'logs': 'logs', 'weights': 'weights'}`, the directories where you want to save your weights and log files from the training session), and NOT `logs_dir`.
Did you find `logs_dir` in the documentation?

**Comment by coco-HJ** [comment]
p{margin-top:0;margin-bottom:0}
    


    You are right.Thank you for your favor!!^^I resolved the problem.The problem is that the code relating with README.txt and the code that relating with notebooks are different.The notebooks's file code is correct.Very thanks for your interest!!Thank you!!
--------- 원본 메일 ---------

    
        보낸사람: Francesco <notifications@github.com>
        받는사람: idealo/image-super-resolution <image-super-resolution@noreply.github.com>
        
            참조: coco-HJ <wapeul.radar4@daum.net>, Author <author@noreply.github.com>
        
        날짜: 19.07.15 18:50 GMT +0900
        제목: Re: [idealo/image-super-resolution] TypeError: __init__() got an
 unexpected ke
        
        
    
    
        Could you show the code you are using?
From the screenshot, I would assume you are using the Trainer class, that accepts the argument log_dirs(which defaults to {'logs': 'logs', 'weights': 'weights'}, the directories where you want to save your weights and log files from the training session), and NOT logs_dir.
Did you find logs_dir in the documentation?

**Comment by cfrancesco** [comment]
Thanks for pointing this out! I'll correct the readme.

**Comment by coco-HJ** [comment]
p{margin-top:0;margin-bottom:0}
    


    You're welcome~!!^^
--------- 원본 메일 ---------

    
        보낸사람: Francesco <notifications@github.com>
        받는사람: idealo/image-super-resolution <image-super-resolution@noreply.github.com>
        
            참조: coco-HJ <wapeul.radar4@daum.net>, Author <author@noreply.github.com>
        
        날짜: 19.07.16 21:32 GMT +0900
        제목: Re: [idealo/image-super-resolution] TypeError: __init__() got an unexpected keyword argument 'logs_dir' (#39)
        
        
    
    
        Thanks for pointing this out! I'll correct the readme.

**Comment by coco-HJ** [comment]
p{margin-top:0;margin-bottom:0}
    


    Hey~ It's me~Could I ask you a question?I want to know how to check the result image.What I mean is how can I check the previous image and the result image for comparison.Thank you!!                                                                                                                                        Seungjin LeeIntern @ WapeulMobile : +82-10-4101-4330                         Address is at the bottom of : www.wapeul.com                                                                             
--------- 원본 메일 ---------

    
        보낸사람: Francesco <notifications@github.com>
        받는사람: idealo/image-super-resolution <image-super-resolution@noreply.github.com>
        
            참조: coco-HJ <wapeul.radar4@daum.net>, Author <author@noreply.github.com>
        
        날짜: 19.07.16 21:32 GMT +0900
        제목: Re: [idealo/image-super-resolution] TypeError: __init__() got an unexpected keyword argument 'logs_dir' (#39)
        
        
    
    
        Thanks for pointing this out! I'll correct the readme.
