### ISSUE TITLE
HDF5 files are just 1kb，I can not use those weights to optimize my own pictures

### ISSUE THREAD

**Issue by MiaoQiaowei** [idealo/image-super-resolution#4]
OSError: Unable to open file (unable to open file: name = 'D:\Download\image-super-resolution-master\image-super-resolution-master\weights\rdn-C6-D20-G64-G064-x2_enhanced-e219.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Thanks in advance

**Comment by cfrancesco** [comment]
Hi,
did you only clone the repository with `git clone`?
If so, this is normal. As mentioned in the documentation:
> [the weights] are stored on git lfs. If you want to download the weights you need to run `git lfs pull` after cloning the repository.
Or have a look at the tutorial, where they are downloaded with a wget.

**Comment by MiaoQiaowei** [comment]
THX， I have successfully solved the problem. Thank you for everything you have done.

> 嗨，
> 你只用克隆存储库`git clone`吗？
> 如果是这样，这是正常的。如文档中所述：
> 
> > [权重]存储在git lfs上。如果要下载`git lfs pull`克隆存储库后需要运行的权重。
> 
> 或者看一下教程，用wget下载它们。

THX， I have successfully solved the problem. Thank you for everything you have done.
