### ISSUE TITLE
ResourceExhaustError

### ISSUE THREAD

**Issue by fadi212** [idealo/image-super-resolution#41]
Hi Dear,
I have a 2GB GPU. When I run a small image lets say of size 200 by 200 or smaller, it runs it with no error. But when I give a bigger image of lets say 400x400, it gives me this error and I could not find on how to set gpu configurations options for the code. Can you please help.

ResourceExhaustedError: OOM when allocating tensor with shape[1,448,480,544] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc

**Comment by datitran** [comment]
As the error says you're running out-of-memory. 2GB is too small. If you want to have a bigger image, you need more memory.

**Comment by cfrancesco** [comment]
Hi,
in the dev branch there already is an option for larger images.
Check out #14 for how to use it. 

I will add it to the main branch AND to the package by the end of the week.

**Comment by fadi212** [comment]
Ok something I did was to resize the image to lower the size and then do prediction. It worked but I don't think it's a good approach. And one thing, I want my model to predict like on cpu it takes a lot of time but do the prediction. I am looking for an accelerated gpu option but couldn't find any.
