### ISSUE TITLE
Issue with RRDN weight hdf5 file

### ISSUE THREAD

**Issue by sebastianheinz** [idealo/image-super-resolution#46]
Hi,

there seems to be an issue with the RRDN weight hdf5 file. When loading it into the RRDN model, it throws an error. File might be corrupted.

Tested it on Colab.

Can you re-upload it?

Thank you.

**Comment by cfrancesco** [comment]
Hi,
I just tested it and it works for me.
Did you have issues with the other weights?
Also, did you download the weights directly from github and/or run `git lfs pull` after cloning the repo as described in the main README and [here](https://github.com/idealo/image-super-resolution/blob/master/weights/sample_weights/README.md)?

**Comment by sebastianheinz** [comment]
Hi Francesco,

I've downloaded the file corresponding to your [Colab tutorial](https://github.com/idealo/image-super-resolution/blob/master/notebooks/ISR_Prediction_Tutorial.ipynb) using `wget`:

`!wget https://github.com/idealo/image-super-resolution/blob/master/weights/sample_weights/rrdn-C4-D3-G32-G032-T10-x4/Perceptual/rrdn-C4-D3-G32-G032-T10-x4_epoch299.hdf5`

Interestingly, while downloading the RRDN weight file the length (file size) seems to be unknown: [See here](https://prnt.sc/ogqa6a)

For the other weight files, it looks like this:
[See here](https://prnt.sc/ogqapv)

Best,
Sebastian

**Comment by cfrancesco** [comment]
Hi,

so the other files point at the raw folder, like so
`https://github.com/idealo/image-super-resolution/raw/master/weights/sample_weights/rrdn-C4-D3-G32-G032-T10-x4/Perceptual/rrdn-C4-D3-G32-G032-T10-x4_epoch299.hdf5`, but apparently this also does not work any longer.
Use this instead:
`!wget https://media.githubusercontent.com/media/idealo/image-super-resolution/master/weights/sample_weights/rrdn-C4-D3-G32-G032-T10-x4/Perceptual/rrdn-C4-D3-G32-G032-T10-x4_epoch299.hdf5`.

I'll be updating the notebook.
Thank for notifying.

**Comment by talvasconcelos** [comment]
@sebastianheinz do you still have the .hdf5 files, could you share them?
