### ISSUE TITLE
How to resume training?

### ISSUE THREAD

**Issue by Masood-Lapeh** [idealo/image-super-resolution#56]
Hi, Nice project. Can you guide me how to resume training? I know **weights_generator** and **weights_discriminator** exist for transfer learning. Should I save some other things or specify anything else ... ? Thank you.

**Comment by cfrancesco** [comment]
Hi, 
sorry for the late reply.
No, the weights are all you need to resume training! If they where saved with a config file, all the rest should be taken care of, but that's still in development. So for now, if you have troubles, just specify the paths to the weights and you should be fine.

**Comment by davenep** [comment]
I got the following error when resuming training from the saved weight file.

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/network.py in _is_hdf5_filepath(filepath)
   1447 
   1448 def _is_hdf5_filepath(filepath):
-> 1449   return (filepath.endswith('.h5') or filepath.endswith('.keras') or
   1450           filepath.endswith('.hdf5'))
"AttributeError: 'PosixPath' object has no attribute 'endswith'"

**Comment by cfrancesco** [comment]
Could you share the entire error message?
