### ISSUE TITLE
cannot download weights 

### ISSUE THREAD

**Issue by suddh123** [idealo/image-super-resolution#57]
Hello 
I am trying to download the weights for the repo into my google colab  but i keep getting this error

![image](https://user-images.githubusercontent.com/20656542/63635292-c2546300-c67e-11e9-8531-d93cce2dc20d.png)

/content/image-super-resolution
batch response: This repository is over its data quota. Purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/idealo/image-super-resolution.git/info/lfs'

Also i failed to run your google colab notebook it now says 

![image](https://user-images.githubusercontent.com/20656542/63635322-13645700-c67f-11e9-9141-11ff005efa6a.png)

Can you help me with this?

**Comment by zakajd** [comment]
I have the same error. It looks like there is no easy fix for that except sharing weights files using Google Drive or any other cloud storage service without limits.

**Comment by datitran** [comment]
Hi this is a problem of Git LFS. We only have 1 GB a month of free bandwidth: https://help.github.com/en/articles/about-storage-and-bandwidth-usage. It seems we ran out of our free bandwidth. Maybe you can try in a few days again.

**Comment by suddh123** [comment]
I tried again today and got the same error clearly the bandwidth is still unavailable . Can you either provide the weights in a google drive or atleast let us know when your git lfs account  will have enough bandwidth??

**Comment by cfrancesco** [comment]
Hi,
they are (prob temporarily) available a google drive link at #57

**Comment by datitran** [comment]
@suddh123 I checked our bandwidth problem and it's actually connected to our billing cycle which will re-start in 12 days. So it's not at the beginning of each month but in the middle of each months. Other than that we're looking into a better solution.
