### ISSUE TITLE
"git lfs pull" error (This repository is over its data quota)

### ISSUE THREAD

**Issue by ldevyataykina** [idealo/image-super-resolution#58]
Getting an error if try git lfs pull afterward:

```
$ git lfs pull
batch response: This repository is over its data quota. Purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/idealo/image-super-resolution.git/info/lfs'
```

**Comment by cfrancesco** [comment]
Hi,
as pointed out in #57 it's a service limit. We will look into an alternative. Try again at the beginning of next month, sorry!

**Comment by cfrancesco** [comment]
Hi,

they are temporarily available on google drive. Look here #59

**Comment by Metatr0n** [comment]
Hi,

I have the same error now

**Comment by ldevyataykina** [comment]
Hi,

I have the same error now
