### ISSUE TITLE
Any chance on getting the sample weights? Drive, Dropbox...

### ISSUE THREAD

**Issue by talvasconcelos** [idealo/image-super-resolution#59]
Can someone please share the old weights files?
rdn-C6-D20-G64-G064-x2_ArtefactCancelling_epoch219.hdf5
and 
rdn-C6-D20-G64-G064-x2/PSNR-driven/rdn-C6-D20-G64-G064-x2_PSNR_epoch086.hdf5

**Comment by siju-samuel** [comment]
Could you please share the weight files?
```

batch response: This repository is over its data quota. Purchase more data packs to restore access.                                                                                                                
error: failed to fetch some objects from 'https://github.com/idealo/image-super-resolution.git/info/lfs'

```

**Comment by pdlje82** [comment]
Hi,
the same for me, the repo is over its data quota :(

**Comment by talvasconcelos** [comment]
I thought maybe someone had it saved in hard drive from previous pulls or clones.

**Comment by tyoc213** [comment]
Maybe some one will donate a gift card? https://github.com/nabla-c0d3/nassl/issues/17

**Comment by CPritch** [comment]
I'll be happy to front the the cost of a few data packs @nabla-c0d3 just drop me a line.

**Comment by nabla-c0d3** [comment]
Cool project! To be honest I don't quite understand how nassl has anything to do with it... Can you explain?

**Comment by CPritch** [comment]
Whoops, followed the link assuming you were the owner. My offer still stands for @cfrancesco or @datitran  though; I've already bought a gift card.

**Comment by tyoc213** [comment]
sorry my fault... it was me linking a possible solution to the problem... thought not permanent... still thinking that just putting them in git is more than enought...

**Comment by cfrancesco** [comment]
Hi everyone,

sorry for the troubles and thank you very much @CPritch for your very kind offer. @datitran and I will look into a proper solution.

For now, here there are:
https://drive.google.com/drive/folders/1cJLPgGfEuFAQzBKbXQtSGXxLXssw1D9f?usp=sharing

Let me know if there is any further issue (I'm not sure how this google drive solution will work out in the long run)/

**Comment by jqueguiner** [comment]
I work for ovh.com and we will provide you something on a cloud storage as it be downloadable form CLI which is not the case for gdrive. I’ve been putting a lot of weights files on public cloud storage just because gdrive doesn’t allow direct download and it’s a pain...

**Comment by datitran** [comment]
Hi @CPritch and @jqueguiner, thanks for your offer and we're happy to take it if your offers still stand. You can send me a PM to my mail datitran@gmail.com. Thanks.

**Comment by datitran** [comment]
We have bandwidth again. Thanks to @CPritch for the gift card. Will close the issue for now.

**Comment by cfrancesco** [comment]
The repo now includes direct download from S3 at model creation, like so:
```
model = RRDN(weights='gans')
```
