### ISSUE TITLE
TypeError: Expected binary or unicode string, got PosixPath('logs/rrdn-C4-D3-G64-G064-T10-x2/2019-08-30_11:46')

### ISSUE THREAD

**Issue by Flyzzz** [idealo/image-super-resolution#60]
I run training，after print training detials，got this error :TypeError: Expected binary or unicode string, got PosixPath('logs/rrdn-C4-D3-G64-G064-T10-x2/2019-08-30_11:46'), can not find where to debug, could you help me ?

**Comment by cfrancesco** [comment]
Could you show the entire error logs?

**Comment by Flyzzz** [comment]
@cfrancesco , error as fellow:
Traceback (most recent call last):
  File "train.py", line 75, in <module>
    monitored_metrics={'val_PSNR_Y': 'max'}
  File "/home/jyyr/zeng/image_sharp/image-super-resolution/ISR/train/trainer.py", line 292, in train
    self
  File "/home/jyyr/zeng/image_sharp/image-super-resolution/ISR/utils/train_helper.py", line 302, in initialize_training
    self.callback_paths['weights'].mkdir(parents=True)
  File "/home/jyyr/anaconda3/envs/ISR/lib/python3.6/pathlib.py", line 1248, in mkdir
    self._accessor.mkdir(self, mode)
  File "/home/jyyr/anaconda3/envs/ISR/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileExistsError: [Errno 17] File exists: 'weights/rrdn-C4-D3-G64-G064-T10-x2/2019-09-02_08:37'

**Comment by Flyzzz** [comment]
sorry, I did not get a record. But I remerber it is about Tensorboard at trainer.py  line 295.

**Comment by daarong** [comment]
I saw the same on Windows where "PosixPath" in my error was "WindowsPath".  It's a bug on line 295 of trainer.py where

`self.tensorboard = TensorBoard(log_dir=self.helper.callback_paths['logs'])`

should be

`self.tensorboard = TensorBoard(log_dir=str((self.helper.callback_paths['logs']).resolve()))`

Possibly you don't need to resolve it, but you DO need to convert the log path from a pathlib object to a string.
