### ISSUE TITLE
cna not get my train model

### ISSUE THREAD

**Issue by Flyzzz** [idealo/image-super-resolution#61]
after training ,80 epochs, I can not find my model under the project folder. The code just ended, but does not tell me where to save the weights  or  something. Anyone got same problom?

**Comment by Flyzzz** [comment]
some train code:
log_dirs = {'logs': '/home/jyyr/zeng/image_sharp/image-super-resolution/logs', 'weights': './weights'}
learning_rate = {'initial_value': 0.0004, 'decay_factor': 0.5, 'decay_frequency': 30}
flatness = {'min': 0.0, 'max': 0.15, 'increase': 0.01, 'increase_frequency': 5}
trainer = Trainer(
    generator=rrdn,
    discriminator=discr,
    feature_extractor=f_ext,
    lr_train_dir='./data/low_res/training/images/cubic_x2',
    hr_train_dir='./data/high_res/training/images/original',
    lr_valid_dir='./data/low_res/validation/images',
    hr_valid_dir='./data/high_res/validation/images',
    loss_weights=loss_weights,
    learning_rate=learning_rate,
    flatness=flatness,
    dataname='image_dataset',
    log_dirs=log_dirs,
    weights_generator=None,
    weights_discriminator=None,
    n_validation=1,
)

trainer.train(
    epochs=80,
    steps_per_epoch=50,
    batch_size=5,
    monitored_metrics={'val_PSNR_Y': 'max'}
)

**Comment by cfrancesco** [comment]
Saving the weights should be automagically done within Keras, which is very silent when something goes wrong while saving them, so I'm not sure what the problem could be.

**Comment by gpoulain** [comment]
I got the same problem.
./weights only shows a .yml file after training.
I have no idea where the issues comes from.

**Comment by slee5777** [comment]
I managed to save my model weights by running `trainer.model.save_weights('file_path.hdf5')`
However, when I loaded the weights for prediction, I got `ValueError: You are trying to load a weight file containing 3 layers into a model with 154 layers.`

During training, I also noticed there was a user warning:
`/usr/local/lib/python3.6/dist-packages/keras/engine/training.py:490: UserWarning: Discrepancy between trainable weights and collected trainable weights, did you set 'model.trainable' without calling 'model.compile' after?
'Discrepancy between trainable weights and collected trainable'`

Could you advise how to set `model.trainable` and `model.compile`?  Please also update README.md accordingly.  Many thanks.

**Comment by cfrancesco** [comment]
Hi,
@Flyzzz @gpoulain, a couple of pointers:
if the weights are not saved, it could be an issue with the metrics you're monitoring (like, the specified metric is not part of the available metrics). In this case however there should be a warning message, so probably not your case.

@slee5777 you have trained a model with three layers. The warning message you are seeing is due to the fact that the Adversaria Network is set non-trainable first, when including it in the ISR model, then it's made trainable again, and compiled, in order to be used as a discriminator. I hope this clears things out. What update to the README.md do you mean?

**Comment by slee5777** [comment]
@cfrancesco as soon as I changed the `monitored_metrics={'val_loss': 'min'}` from `{'val_PSNR_Y': 'max'}`.  The weights file saved automatically without any workaround.  
However, when I using the new weights for prediction: 
`sr_img = rrdn.predict(np.array(img))`
`Image.fromarray(sr_img)`, the output image changed its color tone.  Any idea?

**Comment by cfrancesco** [comment]
@slee5777 that's a common training difficulty. Try to reduce the impact of perceptual loss and GANS and or reduce the learning rate. However, out of topic, I'll close the issue. Feel free to open up a new one should you still have issues.
