### ISSUE TITLE
Don't make the weight folder

### ISSUE THREAD

**Issue by apcc-geoslegend** [idealo/image-super-resolution#67]
Hi all,

There isn't make the weight folder in windows OS because of following function:

> in ISR/utils/utils.py.

```
def get_timestamp():
    ts = datetime.now()
    time_stamp = '{y}-{m:02d}-{d:02d}_{h:02d}:{mm:02d}'.format(
        y=ts.year, m=ts.month, d=ts.day, h=ts.hour, mm=ts.minute
    )
    return time_stamp
```

You know, Windows don't allow a character ':' (colon) as the folder name.

So, it should be changed to other character such as '_' (underscore).

Temporarily, I have modified to a underscore ('_') character.

**Comment by cfrancesco** [comment]
same as #52
