### ISSUE TITLE
Training State-of-the-art super-resolution model for ISR

### ISSUE THREAD

**Issue by PyExtreme** [idealo/image-super-resolution#69]
I have seen that PSNR of RDN is less than that of ESRGANs which is state-of-the-art in 2018 and I think there are some other models which have been newly researched. I am interested to contribute to the project. I think that model change will make a significant impact on performance.

Thanks

**Comment by cfrancesco** [comment]
Yes, relativistic GANs might be a better choice and it will be one of the next steps as soon as the project is active again. 
Feel free to PR any model you should train.
Btw, PSNR is not the perfect metric, so I'd sugget not to make strong decisions based on it.

**Comment by PyExtreme** [comment]
@cfrancesco , sure, could you please tell me what could be good choice of metrics for ISR?

**Comment by cfrancesco** [comment]
Unfortunately I don't have a good answer to this. You could opt for a fine tuned image recognition network. Check this paper for a better understanding
https://arxiv.org/abs/1801.03924
