### ISSUE TITLE
Cannot download pretrained models.

### ISSUE THREAD

**Issue by binhmuc** [idealo/image-super-resolution#72]
I run this command:
"git lfs pull"
batch response: This repository is over its data quota. Purchase more data packs to restore access.                                                                                                                 
error: failed to fetch some objects from 'https://github.com/idealo/image-super-resolution.git/info/lfs'

**Comment by delphixe4** [comment]
see this: https://github.com/idealo/image-super-resolution/issues/59#issuecomment-526940275

**Comment by binhmuc** [comment]
@delphixe4  Many thanks <3
