### ISSUE TITLE
Pre-trained model issue

### ISSUE THREAD

**Issue by bhupinders** [idealo/image-super-resolution#75]
While download the weights (While doing git lfs pull), i am getting the following issue. 
_This repository is over its data quota. Purchase more data packs to restore access._ 

Possible to resolve it or host the weights somewhere else?

Thanks.

**Comment by kaushikmit** [comment]
Same issue here. Do we have a solution?

**Comment by cfrancesco** [comment]
Here
https://github.com/idealo/image-super-resolution/issues/59#issuecomment-526940275
