### ISSUE TITLE
Training breaks on images with "x" in the filename

### ISSUE THREAD

**Issue by AjaxGb** [idealo/image-super-resolution#80]
The `_matching_datasets()` method of `DataHandler` assumes that, if an "x" appears in the low-res image filename, it must be a divider between the main image name and a scale of some kind, as in `some_filex0.5.png`. It will then strip anything after and including the "x" from the low-res name.

This becomes a problem if a filename has a meaningful lowercase x in it. For example, if your input files are both named `some_name_with_x_in_it_035.png`, the method will see

Low res: `some_name_with_`  
High res: `some_name_with_x_in_it_035`

and raise the extremely unhelpful error message "Input/LabelsMismatch".

**Comment by Wazted** [comment]
I created a pull request solving this problem, from starting at the end of the string it will take the last 'x' in the filename so the name+x+scale.extension schema will work even if name there is an 'x'

**Comment by cfrancesco** [comment]
Accepted PR, thanks for the contribution!

**Comment by rdevi-pz** [comment]
I am unable to train cos of the LabelMismatch error. Despite trying to use the same name or as x2 for the LR images, the same error keeps popping up. 
I had followed the convention used in the DIV2K datasets for my image data. 
Using Google Colab notebooks for training.

Could you please help take a look:

Error Message: 
AssertionError                            Traceback (most recent call last)
<ipython-input-4-b8dd28b7db58> in <module>()
     46     weights_generator=None,
     47     weights_discriminator=None,
---> 48     n_validation=180,
     49 )
     50 

2 frames
/gdrive/My Drive/Colab_Notebooks/Toyota/image-super-resolution/ISR/train/trainer.py in __init__(self, generator, discriminator, feature_extractor, lr_train_dir, hr_train_dir, lr_valid_dir, hr_valid_dir, loss_weights, log_dirs, fallback_save_every_n_epochs, dataname, weights_generator, weights_discriminator, n_validation, flatness, learning_rate, adam_optimizer, losses, metrics)
    129             patch_size=self.lr_patch_size,
    130             scale=self.scale,
--> 131             n_validation_samples=None,
    132         )
    133         self.valid_dh = DataHandler(

/gdrive/My Drive/Colab_Notebooks/Toyota/image-super-resolution/ISR/utils/datahandler.py in __init__(self, lr_dir, hr_dir, patch_size, scale, n_validation_samples)
     28         self.logger = get_logger(__name__)
     29         self._make_img_list()
---> 30         self._check_dataset()
     31 
     32     def _make_img_list(self):

/gdrive/My Drive/Colab_Notebooks/Toyota/image-super-resolution/ISR/utils/datahandler.py in _check_dataset(self)
     50         # the order of these asserts is important for testing
     51         assert len(self.img_list['hr']) == self.img_list['hr'].shape[0], 'UnevenDatasets'
---> 52         assert self._matching_datasets(), 'Input/LabelsMismatch'
     53 
     54     def _matching_datasets(self):

AssertionError: Input/LabelsMismatch
