### ISSUE TITLE
File "h5py/h5f.pyx", line 85, in h5py.h5f.open OSError: Unable to open file (file signature not found)?

### ISSUE THREAD

**Issue by mantianlong** [idealo/image-super-resolution#81]
import numpy as np
from PIL import Image
import cv2 as cv

img = Image.open('images/093.jpg')
lr_img = np.array(img)

from ISR.models import RDN

rdn = RDN(arch_params={'C':6, 'D':20, 'G':64, 'G0':64, 'x':2})
rdn.model.load_weights('weights/sample_weights/rdn-C6-D20-G64-G064-x2/ArtefactCancelling/rdn-C6-D20-G64-G064-x2_ArtefactCancelling_epoch219.hdf5')

sr_img = rdn.predict(lr_img)

**Comment by ethan-ou** [comment]
If anyone else is having trouble with this, see #46. The file URLs to the weights have changed so you'll need to update these accordingly in your own projects.

**Comment by leowang7** [comment]
Same issue here, do you find any solution yet?

**Comment by gkrislara** [comment]
how was this issue solved?

**Comment by claysauruswrecks** [comment]
Install git lfs and pull the large files.

**Comment by cfrancesco** [comment]
@gkrislara try avoiding git lfs. Use the API call as in the readme. Alternatively you can find the direct download link under the model file.

**Comment by dokluch** [comment]
> @gkrislara try avoiding git lfs. Use the API call as in the readme. Alternatively you can find the direct download link under the model file.

Sorry, I still don't understand how do I pull weights for transfer learning and pass them as paths to files for trainer object
