### ISSUE TITLE
This project is over the git-lfs data quota

### ISSUE THREAD

**Issue by chadnickbok** [idealo/image-super-resolution#82]
Got this trying to clone the project:

```Error downloading object: weights/sample_weights/rdn-C3-D10-G64-G064-x2/PSNR-driven/rdn-C3-D10-G64-G064-x2_PSNR_epoch134.hdf5 (b769931): Smudge error: Error downloading weights/sample_weights/rdn-C3-D10-G64-G064-x2/PSNR-driven/rdn-C3-D10-G64-G064-x2_PSNR_epoch134.hdf5 (b76993189e63fb34dd46d1d40b40498fdb1e298c04185575a1c634e11c86cffd): batch response: This repository is over its data quota. Purchase more data packs to restore access.```

I recommend you move these files into the repo itself, otherwise github will charge you bandwidth for both your repo *AND* everyone else's forks.

**Comment by Monism1** [comment]
https://github.com/idealo/image-super-resolution/tree/master/weights/sample_weights

**Comment by wwwzbwcom** [comment]
same problem here, anyone has backup of these file plz help :)

**Comment by ethan-ou** [comment]
see issue #59. The maintainers have created a couple of Google Drive links as an alternative for downloading the weights. I believe they also address why they don't have the weights inside the repo itself.

**Comment by cfrancesco** [comment]
Correct, thanks @ethan-ou
