### ISSUE TITLE
Resume training

### ISSUE THREAD

**Issue by JawnWB** [idealo/image-super-resolution#84]
Hello,
I was wondering if you could advise the correct way to resume training a system. My current approach is to create the networks and then load the weights from the last session by explicitly calling discr.model.load_weights (and similarly for rrdn) before calling trainer.train

However, the network losses suggest that the network is being re-initialised rather than resuming from the weights I've given. I see in the script that the train helper has code for loading from a checkpoint, but it doesn't seem to trigger for me, which is why I added the calls to explicitly initialise the weights before calling the trainer, but I am concerned that it is also resetting the weights. Can anyone advise on the correct procedure for resuming training?

cheers,
John

**Comment by RyanYChen** [comment]
While initializing Trainer, assign parameter "weights_generator" and "weights_discriminator" . This may be help.

**Comment by JawnWB** [comment]
Hi!
Thanks :-) For some reason I assumed the weights were initialised when the graph was constructed and didn't check the trainer properly. Thanks for the advice!
