### ISSUE TITLE
Local jupyter server giving error for weight directory

### ISSUE THREAD

**Issue by janakptl00** [idealo/image-super-resolution#86]
I am running a Jupyter notebook on localhost and all the commands run flawlessly except when i start to initialize training, get below mentioned errors. I tried google colab notebook without any problems but can not replicate the same thing with local Jupyter server.

trainer.train(
    epochs=1,
    steps_per_epoch=20,
    batch_size=4,
    monitored_metrics={'val_PSNR_Y': 'max'}
)
---------------------------------------------------------------------------
NotADirectoryError                        Traceback (most recent call last)
<ipython-input-7-d7ac4dd2bd9b> in <module>
      3     steps_per_epoch=20,
      4     batch_size=4,
----> 5     monitored_metrics={'val_PSNR_Y': 'max'}
      6 )

~\AppData\Local\Programs\Python\Python37\lib\site-packages\ISR\train\trainer.py in train(self, epochs, steps_per_epoch, batch_size, monitored_metrics)
    290         self.settings['training_parameters']['batch_size'] = batch_size
    291         starting_epoch = self.helper.initialize_training(
--> 292             self
    293         )  # load_weights, creates folders, creates basename
    294 

~\AppData\Local\Programs\Python\Python37\lib\site-packages\ISR\utils\train_helper.py in initialize_training(self, object)
    300 
    301         self.callback_paths = self._make_callback_paths()
--> 302         self.callback_paths['weights'].mkdir(parents=True)
    303         self.callback_paths['logs'].mkdir(parents=True)
    304         object.settings['training_parameters']['starting_epoch'] = last_epoch

~\AppData\Local\Programs\Python\Python37\lib\pathlib.py in mkdir(self, mode, parents, exist_ok)
   1256             self._raise_closed()
   1257         try:
-> 1258             self._accessor.mkdir(self, mode)
   1259         except FileNotFoundError:
   1260             if not parents or self.parent == self:

NotADirectoryError: [WinError 267] The directory name is invalid: 'weights\\rrdn-C4-D3-G64-G064-T10-x2\\2019-10-28_21:32'

**Comment by cfrancesco** [comment]
It should have been fixed some time ago. Are you using the latest version?

**Comment by jaeseong02** [comment]
I am seeing exactly the same issue. 
I assume missing backslash in the end of the directory name causes this. Any help?

**Comment by jaeseong02** [comment]
I found the semicolon in the time stamp causes the problem. 
your time stamp function has : in the code. it should be removed. 

def get_timestamp():
    ts = datetime.now()
    time_stamp = '{y}-{m:02d}-{d:02d}_{h:02d}:{mm:02d}'.format(
        y=ts.year, m=ts.month, d=ts.day, h=ts.hour, mm=ts.minute
    )
    return time_stamp

**Comment by cfrancesco** [comment]
> I found the semicolon in the time stamp causes the problem.
> your time stamp function has : in the code. it should be removed.
> 
> def get_timestamp():
> ts = datetime.now()
> time_stamp = '{y}-{m:02d}-{d:02d}_{h:02d}:{mm:02d}'.format(
> y=ts.year, m=ts.month, d=ts.day, h=ts.hour, mm=ts.minute
> )
> return time_stamp

Where do you find this function?
In MASTER branch (ISR/utils/utils.py, this is the definition:
```
def get_timestamp():
    ts = datetime.now()
    time_stamp = '{y}-{m:02d}-{d:02d}_{h:02d}{mm:02d}'.format(
        y=ts.year, m=ts.month, d=ts.day, h=ts.hour, mm=ts.minute
    )
    return time_stamp
```

**Comment by jaeseong02** [comment]
I installed ISR using pip on my local drive and found this issue 
AppData\Roaming\Python\Python37\site-packages\ISR\utils\utils.py

I see the person originally reported this issue also has semicolon in the timestamp, which will trigger this issue.

**Comment by cfrancesco** [comment]
@jaeseong02 Thank you, the pip package was not up to date. Now it should work!
