### ISSUE TITLE
Running prediction on GPU

### ISSUE THREAD

**Issue by cesarandreslopez** [idealo/image-super-resolution#9]
Great project, thank you! 

Just wondering if you have been able to run the predictions (not the training) on GPU. Using the Dockerfile.gpu I find that ISR will use the CPU to calculate the prediction and not the GPU.

**Comment by ontheway16** [comment]
Wondering the same.

**Comment by cfrancesco** [comment]
I'm not sure where the problem is. I also have been having issues with Docker and GPU, both training and prediction.
It is not an issue of the models (Keras), as this works fine:
https://colab.research.google.com/drive/1TQcowgep90aFEfw_2oMtRCC79CsQQD4A

**Comment by cesarandreslopez** [comment]
I was planning to separate some time later today to work on the Dockerfile itself and see if I could get the model to predict on tensorflow-gpu instead of tensorflow itself. Will report back here soon.

**Comment by cfrancesco** [comment]
I didn't notice the modifications made to the dockerfile: the new line in the dockerfile `RUN pip install -e .` is the issue.
This installs the packages defined in setup.py, which include tensorflow, not tensorflow-gpu.
It's a known problem that if tensorflow is install, despite using the docker image tensorflow-gpu, the non-gpu version will be used.

**Comment by cesarandreslopez** [comment]
Awesome man. You beat me to it!

**Comment by datitran** [comment]
We should fix this i.e. we should add tensorflow-gpu in an `extras_require` in the setup.py
```
extras_require={
        'tests': ['pytest==4.3.0', 'pytest-cov==2.6.1'],
        'docs': ['mkdocs==1.0.4', 'mkdocs-material==4.0.2'],
        'gpu': ['tensorflow-gpu==1.13.1']
    }
```
And then in the Dockerfile.gpu we can just do
```
pip install -e ".[gpu]"
```

**Comment by datitran** [comment]
Okay there is a problem with my proposed solution as both TensorFlow version would be installed as we have the cpu version in `install_requires`. I'm wondering which version would be used then CPU or GPU. Here's a discussion about this without really any fix: https://github.com/keras-team/keras/issues/6997. Another solution is to move the TF version out of `install_requires` but I wouldn't recommend it or we introduce a `requirements.txt` again but here we need to maintain versions again.

**Comment by cfrancesco** [comment]
Adding 
`RUN pip install -e ".[gpu]" --ignore-installed`
solves the issues. 
Thanks everyone.
