### ISSUE TITLE
Inquiry some questions about RRDN

### ISSUE THREAD

**Issue by AlinaXie** [idealo/image-super-resolution#90]
1. You mentioned on the page that you referenced the structure of ESRGAN, so I want to know whether RRDN is based on the ESRGAN?
2. The parameter you referred in the page is the 'C':4, 'D':3, 'G':64, 'G0':64, 'T':10, is original ESRGAN also use the same parameter and same value?
3. And do you have tested other value of parameter? or this value C':4, 'D':3, 'G':64, 'G0':64, 'T':10, is the best?
4. which epochs you get the best val_generator_PSNR_Y result?

**Comment by cfrancesco** [comment]
Hi
1. Yes
2. I used these parameters to have a fair comparison with RDN a comparable prediction times
3. Yes; it depends on what evaluation metric you use (want fast prediction? using MSE? VGG? etc.)
4. As above, and this varies highly, especially when using an adversarial net. Without gans around 40-60 epochs are enough to get something decent. I would recommend to train at least 120 epochs with the default settings
