### ISSUE TITLE
Cannot training with I set weights_generator

### ISSUE THREAD

**Issue by Jhetnipat** [idealo/image-super-resolution#97]
hi

I cannot training model when I set 
```
weights_generator='weights/rrdn-C4-D3-G64-G064-T10-x6/2020-01-16_1509/rrdn-C4-D3-G64-G064-T10-x6_best-val_generator_PSNR_Y_epoch022.hdf5'
weights_discriminator='weights/rrdn-C4-D3-G64-G064-T10-x6/2020-01-16_1509/srgan-large_best-val_generator_PSNR_Y_epoch022.hdf5'
```
run this
```
trainer.train(
    epochs=80,
    steps_per_epoch=20,
    batch_size=4,
    monitored_metrics={'val_PSNR_Y': 'max'}
)
```
I got error

```
---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

<ipython-input-11-e7f3a3e46eec> in <module>()
      3     steps_per_epoch=20,
      4     batch_size=4,
----> 5     monitored_metrics={'val_PSNR_Y': 'max'}
      6 )

5 frames

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/network.py in _is_hdf5_filepath(filepath)
   1447 
   1448 def _is_hdf5_filepath(filepath):
-> 1449  return (filepath.endswith('.h5') or filepath.endswith('.keras') or filepath.endswith('.hdf5'))
   1450 
   1451 

AttributeError: 'PosixPath' object has no attribute 'endswith'
```
run on **google colab**

**Please help me. Thank you so much.**

**Comment by Jhetnipat** [comment]
hi

I cannot training model when I set 
```
weights_generator='weights/rrdn-C4-D3-G64-G064-T10-x6/2020-01-16_1509/rrdn-C4-D3-G64-G064-T10-x6_best-val_generator_PSNR_Y_epoch022.hdf5'
weights_discriminator='weights/rrdn-C4-D3-G64-G064-T10-x6/2020-01-16_1509/srgan-large_best-val_generator_PSNR_Y_epoch022.hdf5'
```
run this
```
trainer.train(
    epochs=80,
    steps_per_epoch=20,
    batch_size=4,
    monitored_metrics={'val_PSNR_Y': 'max'}
)
```
I got error

```
---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

<ipython-input-11-e7f3a3e46eec> in <module>()
      3     steps_per_epoch=20,
      4     batch_size=4,
----> 5     monitored_metrics={'val_PSNR_Y': 'max'}
      6 )

5 frames

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/network.py in _is_hdf5_filepath(filepath)
   1447 
   1448 def _is_hdf5_filepath(filepath):
-> 1449  return (filepath.endswith('.h5') or filepath.endswith('.keras') or filepath.endswith('.hdf5'))
   1450 
   1451 

AttributeError: 'PosixPath' object has no attribute 'endswith'
```

**Comment by Dejan1969** [comment]
It is bug in trainer.py code, tensorflow don't understand path. ISR use pathlib.path but tensorflow expect os.path
===========================================================================
    def _load_weights(self):
        """
        Loads the pretrained weights from the given path, if any is provided.
        If a discriminator is defined, does the same.
        """
        
        if self.weights_generator:
            self.model.get_layer('generator').load_weights(self.weights_generator)
        
        if self.discriminator:
            if self.weights_discriminator:
                self.model.get_layer('discriminator').load_weights(self.weights_discriminator)
                self.discriminator.model.load_weights(self.weights_discriminator)
============================================================================
Solution is to add os.path.join(path)  
============================================================================
import os
.....

    def _load_weights(self):
        """
        Loads the pretrained weights from the given path, if any is provided.
        If a discriminator is defined, does the same.
        """
        if self.weights_generator:
            self.model.get_layer('generator').load_weights(os.path.join(self.weights_generator))
        
        if self.discriminator:
            if self.weights_discriminator:
                self.model.get_layer('discriminator').load_weights(os.path.join(self.weights_discriminator))
                self.discriminator.model.load_weights(os.path.join(self.weights_discriminator))
============================================================================
Hope this helps

**Comment by cfrancesco** [comment]
Yes, this goes through the helper which converts to the paths to Path format. It is sufficient to convert to string before passing the object.
I'm not sure why these errors are popping up only now..

```
def _load_weights(self):
    """
    Loads the pretrained weights from the given path, if any is provided.
    If a discriminator is defined, does the same.
    """
    if self.weights_generator:
        self.model.get_layer('generator').load_weights(str(self.weights_generator))
    
    if self.discriminator:
        if self.weights_discriminator:
            self.model.get_layer('discriminator').load_weights(str(self.weights_discriminator))
            self.discriminator.model.load_weights(str(self.weights_discriminator))
```

**Comment by grahamwhiteuk** [comment]
I just tripped over this one... you need to pull 1c774a0 into master.
