### ISSUE TITLE
processing a large image? like 20mb to 40 mb large image?

### ISSUE THREAD

**Issue by AndreV84** [idealo/image-super-resolution#98]
is it possible? e.g. with characteristics like  "<PIL.Image.Image image mode=RGB size=20736x15552 at 0x7F0CEB7080>"?
could you provide a sample for large image processing, please?

**Comment by Anafeyka** [comment]
> Не могли бы вы предоставить образец для обработки больших изображений, пожалуйста?

```
import numpy as np
import os
from os.path import expanduser
from PIL import Image
from ISR.models import RDN, RRDN
import tensorflow.compat.v1 as tf

os.environ["CUDA_VISIBLE_DEVICES"]="0" 
tf.disable_v2_behavior()
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
allow_growth_session = tf.Session(config=config)

model = RRDN(weights='gans')

Image.MAX_IMAGE_PIXELS=None

img = Image.open(expanduser('data/input/test/10000x10000.png'))
lr_img = np.array(img)
sr_img = model.predict(lr_img, by_patch_of_size=256)
output = Image.fromarray(sr_img)
output.save(expanduser('data/output.png'))
```
Code works:
Win10
2080ti
32 GB of RAM.
Image 10000x10000 png
RRDNx4
I'm not sure if this is the right solution!

**Comment by cfrancesco** [comment]
Yes, this line
`model.predict(lr_img, by_patch_of_size=256, padding_size=20)`
this is the right solution. 
Change the value of by_path_of_size (larger= faster but needs more memory) and increase padding_size if there are some artefacts.
